// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pelo contato */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
          /** INT - use sql.int() */
          w: SQLNumberMarker;
        };
        result: Array<{
          /** Nome do vendedor responsavel pelo contato */
          vendedor: string;
          /** Posicao do cliente dentro da carteira do vendedor (1 = maior score) */
          ordem: number;
          /** ID unico do cliente */
          cliente_id: number;
          /** Nome oficial do cliente */
          razao_social: string;
          /** Cidade do cliente */
          cidade: string;
          /** Unidade federativa (estado) do cliente */
          uf: string;
          /** @sqlType DOUBLE */
          score: number;
          /** NTILE(4): Fria, Morna, Quente, Muito quente */
          faixa: string;
          /** @sqlType DOUBLE */
          ticket_medio: number;
          /** Frase em portugues explicando por que este cliente esta na fila */
          motivo: string;
          /** SKU mais comprado na marca preferida que o cliente nao comprou nos ultimos 90 dias */
          sugestao: string;
          /** Resultado da ligacao: vendeu, vai_pensar, sem_interesse, nao_atendeu */
          retorno_status: string;
          /** Texto livre do vendedor sobre a ligacao */
          retorno_comentario: string;
          /** Data e hora em que o retorno foi registrado */
          retorno_em: string;
          /** E-mail de quem estava logado ao registrar */
          retorno_por: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
          /** INT - use sql.int() */
          w: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          taxa_base_pct: number;
          /** @sqlType DATE */
          referencia_fila: string;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          venderam: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor responsavel pelo contato */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType DOUBLE */
          score_medio: number;
        }>;
      };
  }
}
